<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'Katzgrau\\KLogger\\' => array($vendorDir . '/katzgrau/klogger/src'),
    'Inpsyde\\WPRESTStarter\\' => array($vendorDir . '/inpsyde/wp-rest-starter/src'),
    'GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'Calcurates\\RESTAPI\\' => array($baseDir . '/RESTAPI'),
    'Calcurates\\Controllers\\' => array($baseDir . '/Controllers'),
);
