<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd1586ec25e49b2f24406696684c44569
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Calcurates\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Calcurates\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd1586ec25e49b2f24406696684c44569::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd1586ec25e49b2f24406696684c44569::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
